<?php

acf_add_local_field_group(
	array(
		'key' => 'fontimator-font-options',
		'title' => 'Fontimator Font Options',
		'fields' => array(
			array(
				'key' => 'field_5b790851b929a',
				'label' => 'מחיר בסיס למשקל',
				'name' => 'font_price_base',
				'type' => 'number',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 285,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5b828fc2bdfa9',
				'label' => 'משקלים שכלולים בחבילת ״משפחה בסיסית״',
				'name' => 'familybasic_weights',
				'type' => 'taxonomy',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => 'pa_' . FTM_WEIGHT_ATTRIBUTE,
				'field_type' => 'multi_select',
				'add_term' => 0,
				'save_terms' => 0,
				'load_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
				'allow_null' => 1,
			),
			array(
				'key' => 'field_5b828fc2bdfarchived_weights',
				'label' => 'משקלים שזכרונם לברכה (הועברו לארכיון)',
				'name' => 'archived_weights',
				'type' => 'taxonomy',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => 'pa_' . FTM_WEIGHT_ATTRIBUTE,
				'field_type' => 'multi_select',
				'add_term' => 0,
				'save_terms' => 0,
				'load_terms' => 0,
				'return_format' => 'object',
				'multiple' => 0,
				'allow_null' => 1,
			),
			array(
				'key' => 'field_5b5346members_only',
				'label' => 'פונט למנויים בלבד?',
				'name' => 'members_only',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'product',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	)
);
