<?php

acf_add_local_field_group(
	array(
		'key' => 'fontimator-options',
		'title' => 'Fontimator Configuration',
		'fields' => array(
			array(
				'key' => 'field_5b7bce9c0d896',
				'label' => 'Fonts Path',
				'name' => 'fonts_path',
				'type' => 'text',
				'instructions' => 'Enter the fonts folder path, without slashes (/)',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'fonts',
				'placeholder' => 'fonts',
				'prepend' => content_url() . '/',
				'append' => '/',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5b7bcf070d897',
				'label' => 'Site Prefix',
				'name' => 'site_prefix',
				'type' => 'text',
				'instructions' => 'Short prefix for the files',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'fm',
				'placeholder' => 'xx',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5b7bcf480d898',
				'label' => 'Site Name',
				'name' => 'site_name',
				'type' => 'text',
				'instructions' => 'Lowercase',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Fontimator',
				'placeholder' => 'Fontimator',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5b7bcf720d899',
				'label' => 'License Attribute',
				'name' => 'license_attribute',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'license',
				'placeholder' => 'license',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5b7bd1d3f1689',
				'label' => 'Weight Attribute',
				'name' => 'weight_attribute',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'weight',
				'placeholder' => 'weight',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'ftm_specimen_filename_prefix',
				'label' => 'Specimen Filename Prefix',
				'name' => 'specimen_filename_prefix',
				'type' => 'text',
				'instructions' => 'The filename of the specimens for each font. i.e. - <code>fonts/ploni/_____-ploni.pdf</code>',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'specimen',
				'placeholder' => 'specimen',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5be81a9db495f',
				'label' => 'License Information Page',
				'name' => 'license_info_page',
				'type' => 'page_link',
				'instructions' => 'The license info page, to be linked in various places. (e.g. the info icon on variation picking form)',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'page',
				),
				'taxonomy' => '',
				'allow_null' => 0,
				'allow_archives' => 1,
				'multiple' => 0,
			),
			array(
				'key' => 'ftm_display_family_discount_percentage',
				'label' => 'Display Family Discount Percentages',
				'name' => 'display_family_discount_percentage',
				'type' => 'true_false',
				'instructions' => 'On select box on single font page',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 1,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'fontimator-config',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
		'width' => '50%',
	)
);
