<?php

acf_add_local_field_group(
	array(
		'key' => 'fontimator-wsms-gifts',
		'title' => 'WSMS MailChimp Font Gifts Settings',
		'fields' => array(
			array(
				'key' => 'field_5bb4b99c46a40',
				'label' => 'MailChimp Font Gifts Fields',
				'name' => 'mailchimp_font_gifts',
				'type' => 'repeater',
				'instructions' => 'Enter here the merge fields from MailChimp, and assign them to fonts on this website.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_5bb4ba3546a42',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => 'Add new gift font...',
				'sub_fields' => array(
					array(
						'key' => 'field_5bb4b9da46a41',
						'label' => 'Merge Field',
						'name' => 'merge_field',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'FG_',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5bb4ba3546a42',
						'label' => 'Font Product',
						'name' => 'font_product',
						'type' => 'post_object',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'post_type' => array(
							0 => 'product',
						),
						'taxonomy' => array(),
						'allow_null' => 0,
						'multiple' => 0,
						'return_format' => 'id',
						'ui' => 1,
					),
					array(
						'key' => 'field_5bb4bd2b25c2f',
						'label' => 'Font Weight',
						'name' => 'font_weight',
						'type' => 'taxonomy',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'taxonomy' => 'pa_weight',
						'field_type' => 'select',
						'allow_null' => 0,
						'add_term' => 0,
						'save_terms' => 0,
						'load_terms' => 0,
						'return_format' => 'object',
						'multiple' => 0,
					),
					array(
						'key' => 'field_5bb4bd6725c30',
						'label' => 'Font License',
						'name' => 'font_license',
						'type' => 'taxonomy',
						'instructions' => 'Defaults to otf-2',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'taxonomy' => 'pa_license',
						'field_type' => 'select',
						'allow_null' => 1,
						'add_term' => 0,
						'save_terms' => 0,
						'load_terms' => 0,
						'return_format' => 'object',
						'multiple' => 0,
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'fontimator-config',
				),
			),
		),
		'menu_order' => 10,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	)
);
